server:
  port: 8093
  servlet:
    context-path: /fpa
  error:
    include-message: ALWAYS

spring:
  application:
    name: fiserv-payment-adapter
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      client:
        config:
          card-tokenization-service:
            url: https://token-sandbox.dev.clover.com
            loggerLevel: FULL
          ecommerce-service:
            url: https://scl-sandbox.dev.clover.com
            loggerLevel: FULL


springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true

logging:
  level:
    root: INFO
    org:
      dipocket: DEBUG
    io.synapto.payment.adapter.fiserv.client: DEBUG

